app/controllers/blueprints/network_routes.py
from flask import Blueprint, request, render_template, flash
from flask_login import current_user, login_required, fresh_login_required
from app.controllers.networks import set_interface_unit, \
    get_interface_summary, get_interface_configuration

from app.controllers.forms import NetworkForm
from app.models import Users, Devices
from app import db

from cryptography.fernet import Fernet

# Inicializa o Blueprint
network_bp = Blueprint('network', __name__)

f = Fernet(b'bdilxeLGCHnJo-2HtofB9wGcXaUV7D5NZgxh5Nt5fpg=')


# Rota: get_interface_summary
@network_bp.route('/get_interface_summary', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def interface_summary():
    form = NetworkForm()

    devices = db.session.execute(db.select(Devices)).scalars().all()

    current_user_record = db.session.execute(
        db.select(Users).filter_by(username=current_user.username)
    ).scalar_one_or_none()

    user_decrypted_password = f.decrypt(current_user_record.password).decode('utf-8')  # noqa: E501

    output = None

    if request.method == 'POST':
        selected_hostname = form.hostname.data
        logged_username = current_user.username
        user_password = user_decrypted_password

        output = get_interface_summary(
            selected_hostname,
            logged_username,
            user_password,
        )

        flash('Comando enviado com sucesso!', category='success')

    else:
        if form.errors:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f"Erro no campo {field}: {error}", category='danger')

    return render_template(
        'route/get_interface_summary.html',
        form=form,
        output=output,
        devices=devices,
    )


# Rota: get_interface_configuration
@network_bp.route('/get_interface_configuration', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def interface_configuration():
    form = NetworkForm()

    devices = db.session.execute(db.select(Devices)).scalars().all()

    output = None

    current_user_record = db.session.execute(
        db.select(Users).filter_by(username=current_user.username)
    ).scalar_one_or_none()

    user_decrypted_password = f.decrypt(current_user_record.password).decode('utf-8')  # noqa: E501

    if request.method == 'POST':
        hostname = form.hostname.data
        username = current_user.username
        password = user_decrypted_password
        unit = request.form.get('unit')

        output = get_interface_configuration(
            hostname, username, password, unit
        )

        flash('Comando enviado com sucesso!', category='success')

    else:
        if form.errors:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f"Erro no campo {field}: {error}", category='danger')

    return render_template(
        'route/get_interface_configuration.html',
        form=form,
        output=output,
        devices=devices,
    )


# Rota: set_interface_unit
@network_bp.route('/set_interface_unit', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def interface_unit():
    form = NetworkForm()

    current_user_record = db.session.execute(
        db.select(Users).filter_by(username=current_user.username)
    ).scalar_one_or_none()

    user_decrypted_password = f.decrypt(current_user_record.password).decode('utf-8')  # noqa: E501

    output = None

    hosts = db.session.execute(db.select(Devices).order_by(Devices.id)).scalars()  # noqa: E501

    form.hostname.choices = [(host.ip_address, host.hostname) for host in hosts]  # noqa: E501

    if form.validate_on_submit():
        hostname = form.hostname.data
        username = current_user.username
        password = user_decrypted_password
        unit = form.unit_vlan.data
        description = form.description.data
        bandwidth = form.bandwidth.data
        ipv4_gw = form.ipv4_gw.data
        ipv6_gw = form.ipv6_gw.data
        ipv6_cli = form.ipv6_cli.data
        inet6_48 = form.ipv6_48.data

        output = set_interface_unit(
            hostname, username, password, unit, description,
            bandwidth, ipv4_gw, ipv6_gw, ipv6_cli, inet6_48
        )

        flash('Comando enviado com sucesso!', category='success')

    else:
        if form.errors:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f"Erro no campo {field}: {error}", category='danger')

    return render_template(
        'route/set_interface_unit.html',
        form=form,
        output=output,
    )

app/templates/route/get_interface_configuration.html
{% extends "layout.html" %}

{% block content %}
<h1 class="display-4">{% block title %}Get Configuration{% endblock %}</h1>

{% block comment %}
{{ super() }}
{% endblock %}
<hr>

<form method="POST" action="{{url_for('network.interface_configuration')}}" autocomplete="off">
    <div class="form-row">
        <!-- Routers -->
        <div class="form-group col">
            <select name="hostname" id="hostname" class="form-control">
                {% for device in devices %}
                <option value="{{device.ip_address}}">{{device.hostname}}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Unit/Vlan -->
        <div class="form-group col">
            <input type="number" class="form-control" name="unit" id="unit" placeholder="Unit Vlan" required>
        </div>
    </div>

    <div class="form-row">
        <!-- Usuários -->
        <div class="form-group col mb-3">
            <input type="text" class="form-control" value="{{ current_user.username }}" readonly>
        </div>

        <!-- Passwords -->
        <div class="input-group col mb-3">
            <input type="password" class="form-control" id="password-input" value="{{ current_user.password[:12] }}"
                readonly>
            <div class="input-group-append">
                <i class="fas fa-eye input-group-text" id="toggle-password"></i>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

<br>

<pre class="text-center"> show configuration interfaces ae0 unit {unit} </pre>

<pre class="max-height" style=" border: solid 1px rgba(0, 0, 0, .1); 
                                    padding: 1rem; 
                                    margin-top: 1rem; 
                                    border-radius: 10px;">{{ output }}</pre>
{% endblock %}

app/templates/route/get_interface_summary.html
{% extends "layout.html" %}

{% block content %}
<h1 class="display-4">{% block title %}Get Summary{% endblock %}</h1>

{% block comment %}
{{ super() }}
{% endblock %}

<hr>

<form method="POST" action="{{ url_for('network.interface_summary') }}" autocomplete="off">
    {{ form.hidden_tag() }}

    <div class="form-row">
        <!-- Routers -->
        <div class="form-group col">
            <select name="hostname" id="hostname" class="form-control">
                {% for device in devices %}
                <option value="{{ device.ip_address }}">{{ device.hostname }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-row">
        <!-- Usuários -->
        <div class="form-group col mb-3">
            <input type="text" class="form-control" value="{{ current_user.username }}" readonly>
        </div>

        <!-- Passwords -->
        <div class="input-group col mb-3">
            <input type="password" class="form-control" id="password-input" value="{{ current_user.password[:12] }}"
                readonly>
            <div class="input-group-append">
                <i class="fas fa-eye input-group-text" id="toggle-password"></i>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

<br>

<pre class="text-center">show interfaces terse lo0 | match lo</pre>

<pre class="max-height" style=" border: solid 1px rgba(0, 0, 0, .1); 
                                    padding: 1rem; 
                                    margin-top: 1rem; 
                                    border-radius: 10px;">{{ output }}</pre>
{% endblock %}

app/templates/route/set_interface_unit.html
{% extends "layout.html" %} {% block content %}
<h1 class="display-4">{% block title %}Set Config interface{% endblock %}</h1>

{% block comment %}
{{ super()}}
{% endblock %}

<hr />

<form action="{{url_for('network.interface_unit')}}" method="POST" autocomplete="off">
  {{ form.hidden_tag() }}
  <!-- ROW -->
  <div class="form-row">
    <div class="form-group col">{{ form.hostname(class="form-control") }}</div>
  </div>

  <!-- ROW -->
  <div class="form-row">
    <div class="form-group col-3">
      {{ form.unit_vlan(class="form-control", placeholder="Unit VLAN") }}
    </div>
    <div class="form-group col">
      {{ form.description(class="form-control", placeholder="Description") }}
    </div>
  </div>

  <!-- ROW -->
  <div class="form-row">
    <div class="form-group col-4">
      {{ form.ipv4_gw(class="form-control", placeholder="Gateway - IPv4") }}
    </div>
    <div class="form-group col">
      {{ form.bandwidth(class="form-control", placeholder="Bandwidth") }}
    </div>
  </div>

  <!-- ROW -->
  <div class="form-row">
    <div class="form-group col-4">
      {{ form.ipv6_gw(class="form-control", placeholder="ipv6_gw") }}
    </div>
    <div class="form-group col-4">
      {{ form.ipv6_cli(class="form-control", placeholder="ipv6_cli") }}
    </div>
    <div class="form-group col-4">
      {{ form.ipv6_48(class="form-control", placeholder="ipv6_48") }}
    </div>
  </div>

  <!-- ROW -->
  <div class="form-row">
    <!-- Usuários -->
    <div class="form-group col mb-3">
      <input type="text" class="form-control" value="{{ current_user.username }}" readonly>
    </div>

    <!-- Passwords -->
    <div class="input-group col mb-3">
      <input type="password" class="form-control" id="password-input" value="{{ current_user.password[:12] }}" readonly>
      <div class="input-group-append">
        <i class="fas fa-eye input-group-text" id="toggle-password"></i>
      </div>
    </div>
  </div>

  {{ form.submit(class="btn btn-primary") }}
</form>

<br>

<pre class="text-center">set interfaces ae0 unit {unit}</pre>

<pre class="max-height" style="
    border: solid 1px rgba(0, 0, 0, 0.1);
    padding: 1rem;
    margin-top: 1rem;
    border-radius: 10px;
  ">
{{ output }}
</pre>

{% endblock %}