app/controllers/blueprints/auth_routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, login_user, logout_user
from app import db
from app.models import Users
from app.controllers.forms import LoginForm
from cryptography.fernet import Fernet

auth_bp = Blueprint('auth', __name__)


def check_password(stored_password, provided_password):
    f = Fernet(b'bdilxeLGCHnJo-2HtofB9wGcXaUV7D5NZgxh5Nt5fpg=')

    try:
        decrypted_password = f.decrypt(stored_password).decode('utf-8')
        return decrypted_password == provided_password
    except Exception as e:
        print(f'[Erro] Falha ao verificar a senha: {e}')
        return False


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()

    if login_form.validate_on_submit():
        input_username = login_form.username.data
        input_password = login_form.password.data

        user_record = db.session.execute(
            db.select(Users).filter_by(username=input_username)
        ).scalar_one_or_none()

        if user_record and check_password(user_record.password, input_password):  # noqa: E501
            login_user(user_record, remember=login_form.checkbox.data)
            flash(f'Sucesso ao logar {input_username}', category='success')
            return redirect(url_for('network.interface_summary'))
        else:
            flash('Usuário ou senha incorretos', category='danger')

    if login_form.errors:
        for field_name, error_messages in login_form.errors.items():
            for error_message in error_messages:
                flash(f'Erro no campo {field_name}: {error_message}', category='danger')  # noqa: E501
    return render_template('login.html', form=login_form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Deslogado!!!', category='info')
    return redirect(url_for('auth.login'))

app/controllers/blueprints/network_routes.py
from flask import Blueprint, request, render_template, flash
from flask_login import current_user, login_required, fresh_login_required
from app.controllers.networks import set_interface_unit, \
    get_interface_summary, get_interface_configuration

from app.controllers.forms import NetworkForm
from app.models import Users, Devices
from app import db

from cryptography.fernet import Fernet

# Inicializa o Blueprint
network_bp = Blueprint('network', __name__)

f = Fernet(b'bdilxeLGCHnJo-2HtofB9wGcXaUV7D5NZgxh5Nt5fpg=')


# Rota: get_interface_summary
@network_bp.route('/get_interface_summary', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def interface_summary():
    form = NetworkForm()

    devices = db.session.execute(db.select(Devices)).scalars().all()

    current_user_record = db.session.execute(
        db.select(Users).filter_by(username=current_user.username)
    ).scalar_one_or_none()

    user_decrypted_password = f.decrypt(current_user_record.password).decode('utf-8')  # noqa: E501

    output = None

    if request.method == 'POST':
        selected_hostname = form.hostname.data
        logged_username = current_user.username
        user_password = user_decrypted_password

        output = get_interface_summary(
            selected_hostname,
            logged_username,
            user_password,
        )

        flash('Comando enviado com sucesso!', category='success')

    else:
        if form.errors:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f"Erro no campo {field}: {error}", category='danger')

    return render_template(
        'route/get_interface_summary.html',
        form=form,
        output=output,
        devices=devices,
    )


# Rota: get_interface_configuration
@network_bp.route('/get_interface_configuration', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def interface_configuration():
    form = NetworkForm()

    devices = db.session.execute(db.select(Devices)).scalars().all()

    output = None

    current_user_record = db.session.execute(
        db.select(Users).filter_by(username=current_user.username)
    ).scalar_one_or_none()

    user_decrypted_password = f.decrypt(current_user_record.password).decode('utf-8')  # noqa: E501

    if request.method == 'POST':
        hostname = form.hostname.data
        username = current_user.username
        password = user_decrypted_password
        unit = request.form.get('unit')

        output = get_interface_configuration(
            hostname, username, password, unit
        )

        flash('Comando enviado com sucesso!', category='success')

    else:
        if form.errors:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f"Erro no campo {field}: {error}", category='danger')

    return render_template(
        'route/get_interface_configuration.html',
        form=form,
        output=output,
        devices=devices,
    )


# Rota: set_interface_unit
@network_bp.route('/set_interface_unit', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def interface_unit():
    form = NetworkForm()

    current_user_record = db.session.execute(
        db.select(Users).filter_by(username=current_user.username)
    ).scalar_one_or_none()

    user_decrypted_password = f.decrypt(current_user_record.password).decode('utf-8')  # noqa: E501

    output = None

    hosts = db.session.execute(db.select(Devices).order_by(Devices.id)).scalars()  # noqa: E501

    form.hostname.choices = [(host.ip_address, host.hostname) for host in hosts]  # noqa: E501

    if form.validate_on_submit():
        hostname = form.hostname.data
        username = current_user.username
        password = user_decrypted_password
        unit = form.unit_vlan.data
        description = form.description.data
        bandwidth = form.bandwidth.data
        ipv4_gw = form.ipv4_gw.data
        ipv6_gw = form.ipv6_gw.data
        ipv6_cli = form.ipv6_cli.data
        inet6_48 = form.ipv6_48.data

        output = set_interface_unit(
            hostname, username, password, unit, description,
            bandwidth, ipv4_gw, ipv6_gw, ipv6_cli, inet6_48
        )

        flash('Comando enviado com sucesso!', category='success')

    else:
        if form.errors:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f"Erro no campo {field}: {error}", category='danger')

    return render_template(
        'route/set_interface_unit.html',
        form=form,
        output=output,
    )

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <!-- Meta tags Obrigatórias -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css' )}}">
  <title>{% block title %}Automation python{% endblock %}</title>
</head>

<body class="container">

  <nav aria-label="breadcrumb">
    <ul class="breadcrumb">
      <a class="breadcrumb-item" href="{{url_for('index')}}">Home</a>
      <a class="breadcrumb-item" href="{{url_for('sh_config_int_unit')}}">unit</a>
      <a class="breadcrumb-item" href="{{url_for('page_cadastro')}}">Cadastro</a>
    </ul>
  </nav>

  <div class="jumbotron">
  {% block content %}

  {% endblock content %}
</div>

  <!-- JavaScript (Opcional) -->
  <script src="{{url_for('static',filename='js/main.js')}}"></script>
  <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
</body>

</html>

app/templates/head.html
<!-- Meta Tags Obrigatórias -->
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

<!-- Title do Site -->
<title>{% block title %}auto.clickip.local{% endblock %}</title>

<!-- FontAwesome -->
<script src="https://kit.fontawesome.com/19bb9c4807.js" crossorigin="anonymous">
</script>

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
<!-- CSS Personalizado -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
    integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous">
    </script>
<!-- Popper.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
    </script>
<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
    </script>
<!-- JS Personalizado -->
<script src="{{ url_for('static', filename='js/main.js') }}"></script>

app/templates/home.html
{% extends 'layout.html' %} {% block content %}
<h1 class="display-4">{% block title %}Home{% endblock %}</h1>
<p class="lead">
  Aplicação Flask para automatizar configurações de rede, integrando validação
  de endereços IPv4/IPv6, autenticação de usuários e registro de dispositivos,
  com suporte a Netmiko para execução de comandos SSH.
</p>
<hr />

<pre class="pre-scrollable max-height" style="
    border: solid 1px rgba(0, 0, 0, 0.1);
    padding: 1rem;
    margin-top: 1rem;
    border-radius: 10px;
  ">
{{ output }}</pre>
{% endblock %}

app/templates/home_old.html
{% extends 'layout.html' %}

{% block content %}

    <h1 class="display-4">{% block title %}Home{% endblock %}</h1>
    <p class="lead">Este é um simples componente jumbotron para chamar mais atenção a um determinado conteúdo ou informação.</p>
    
    <hr>

    <form method="POST" action="{{url_for('page_home')}}" autocomplete="off">

        <div class="form-group">
            <label for="host">Router</label>
            <select name="host" id="host" class="form-control">
                <option value="143.137.92.254">vroute</option>
                <option value="170.84.29.254">bgp</option>
            </select>
            <small class="form-text text-muted">IP Address do equipamento</small>
        </div>
        
        <!-- Tacacs -->
        <div class="form-group">
            <select name="username" id="username" class="form-control">
                <label for="username">Selecione um usuário</label>
                <option value="fabio.ewerton">fabio.ewerton</option>
                <option value="glicia.santos">glicia.santos</option>
                <option value="leo.duarte">leo.duarte</option>
                <option value="roger.ochiai">roger.ochiai</option>
            </select>
        </div>
        
        <div class="form-group">
            <label for="password"  hidden></label>
            <input type="password" class="form-control" name="password" id="password" placeholder="Senha" required>
            <small class="form-text text-muted">Senha do tacacs</small>
        </div>

        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
    <pre class="pre-scrollable max-height" style="
                border: solid 1px rgba(0, 0, 0, .1); 
                padding: 1rem; 
                margin-top: 1rem; 
                border-radius: 10px;">{{ output }}</pre>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  {% include 'head.html' %}
  <title>{% block title %}Home{% endblock title %}</title>
</head>

<body class="container">

  <!-- Breadcrumb and Menus -->
  <div class="d-flex justify-content-between">

    <!-- Left Side Menu -->
    <nav aria-label="breadcrumb">
      <ul class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{ url_for('page_home') }}">Home</a>
        </li>
        <li class="dropdown ml-3">
          <a href="#" class="dropdown-toggle mr-3" type="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            Routers
          </a>
          <div class="dropdown-menu">
            <a href="{{ url_for('network.interface_summary') }}" class="dropdown-item">Interface Summary</a>
            <a href="{{ url_for('network.interface_configuration') }}" class="dropdown-item">Interface Configuration</a>
            <a href="{{ url_for('network.interface_unit') }}" class="dropdown-item">Config Interface Unit Vlan</a>
            <a href="#" class="dropdown-item">Config Static Router</a>
          </div>
        </li>
      </ul>
    </nav>

    <!-- Right Side Menu -->
    <nav class="breadcrumb">
      {% if current_user.is_authenticated %}
      <span class="mr-3 text-uppercase font-weight-light">
        &#8764; {{ current_user.username }} &#8764;
      </span>
      <a class="breadcrumb-item" href="{{ url_for('auth.logout') }}">Logout</a>
      {% else %}
      <a class="breadcrumb-item" href="{{ url_for('auth.login') }}">Login</a>
      {% endif %}
    </nav>

  </div>

  <!-- Jumbotron -->
  <div class="jumbotron">

    <!-- Flash Messages -->
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
      <p class="m-auto">{{ message }}</p>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close" aria-hidden="true">
        &times;
      </button>
    </div>
    {% endfor %}
    {% endwith %}


    <!-- Site Content -->
    {% block content %}
    data

    {% block comment %}
    <p class="lead">
      Aplicação Flask para automatizar configurações de rede, integrando validação
      de endereços IPv4/IPv6, autenticação de usuários e registro de dispositivos,
      com suporte a Netmiko para execução de comandos SSH.
    </p>
    {% endblock comment %}

    {% endblock content %}

  </div>

</body>

app/templates/login.html
{% extends "layout.html" %}

{% block content %}
<h1 class="display-4">{% block title %}Login{% endblock %}</h1>

{% block comment %}
{{ super() }}
{% endblock %}

<hr>
<form method="POST" action="{{url_for('auth.login')}}" autocomplete="off">
    {{ form.hidden_tag() }}

    <div class="form-group">
        {{ form.username(class="form-control mb-3", placeholder='user.name') }}

        <div class="input-group">
            {{ form.password(class="form-control", placeholder='password', id='password-input') }}
            <div class="input-group-append">
                <i class="fas fa-eye input-group-text" id="toggle-password"></i>
            </div>
        </div>
    </div>


    <div class="d-flex justify-content-between align-items-center">
        {{ form.submit(class='btn btn-primary') }}
        <div class="custom-control custom-checkbox">
            {{ form.checkbox(class="custom-control-input") }}
            {{ form.checkbox.label(class="custom-control-label") }}
        </div>
    </div>
</form>

{% endblock %}

app/templates/page_edit_user.html
{% extends "layout.html" %}

{% block content %}
<h1 class="display-4">{% block title %}Edit User{% endblock %}</h1>
<p class="lead">Este é um simples componente jumbotron para chamar mais atenção a um determinado conteúdo ou informação.
</p>

<hr>

<form method="POST" action="{{ url_for('page_edit_user', id=user.id) }}">
    {{ form.hidden_tag() }}
    <label for="username" hidden></label>
    {{ form.username(class='form-control') }}
    <br>
    
    <label for="username" hidden></label>
    {{ form.password(class='form-control', placeholder='new password') }}
    <br>
    
    <label for="username" hidden></label>
    {{ form.password_confirm(class='form-control', placeholder='confirm your new password') }}
    <br>{{ form.submit(class='btn btn-primary') }}
</form>

{% endblock %}


place

app/templates/page_register_user.html
{% extends "layout.html" %}

{% block content %}
<h1 class="display-4">{% block title %}Cadastro{% endblock %}</h1>
<p class="lead">Este é um simples componente jumbotron para chamar mais atenção a um determinado conteúdo ou informação.
</p>

<hr>

<form action="{{url_for('page_register')}}" method="POST">
    {{ form.hidden_tag() }}

    <label for="username" hidden></label>
    {{ form.username(class='form-control', placeholder='user.name')}}
    <br>

    <label for="password" hidden></label>
    {{ form.password(class='form-control', placeholder='Password') }}
    <br>

    <label for="password_confirm" hidden></label>
    {{ form.password_confirm(class='form-control', placeholder='Confirme Senha') }}
    <br>

    <div class="d-flex justify-content-between">
        {{ form.submit(class='btn btn-sm btn-primary') }}
        <a class="btn btn-sm btn-secondary" href="{{url_for('page_login')}}">Login</a>
    </div>
</form>
<br>

<table class="table table-sm table-striped">
    <caption>Usuario Cadastrados</caption>
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">Ação</th>
        </tr>
    </thead>
    <tbody>
        {% for tab in table %}
        <tr>
            <td> {{ tab.id}} </td>
            <td> {{ tab.username}} </td>
            <td>
                <a href="{{tab.id}}/edit_user" class="btn btn-sm btn-primary px-3">Editar</a>
                <a href="{{tab.id}}/remove_user" class="btn btn-sm btn-danger px-3">Excluir</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/register.html
{% extends "layout.html" %}

{% block content %}
<h1 class="display-4">{% block title %}Cadastro{% endblock %}</h1>
<p class="lead">Este é um simples componente jumbotron para chamar mais atenção a um determinado conteúdo ou informação.
</p>

<hr>

<form action="{{url_for('page_register')}}" method="POST">
    {{ form.hidden_tag() }}

    <label for="email" hidden></label>
    {{ form.email(class='form-control', placeholder='E-mail')}}
    <small class="form-text text-muted">E-mail corporativo</small>
    <br>

    <label for="password" hidden></label>
    {{ form.password(class='form-control', placeholder='Password') }}
    <small class="form-text text-muted">Informe sua senha</small>
    <br>

    <label for="password_confirm" hidden></label>
    {{ form.password_confirm(class='form-control', placeholder='Confirme Senha') }}
    <small class="form-text text-muted">Confirme Senha</small>
    <br>

    <div class="d-flex justify-content-between">
        {{ form.submit(class='btn btn-primary') }}
        <a class="btn btn-secondary" href="{{url_for('page_login')}}">Login</a>
    </div>
</form>
{% endblock %}

app/templates/registered_users.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="display-4">{% block title %}Home{% endblock %}</h1>
<p class="lead">Este é um simples componente jumbotron para chamar mais atenção a um determinado conteúdo ou informação.
</p>

<hr>

<!-- users -->
<select name="" id="" class="form-control">
    {% for tab in table %}
    <option value="{{ tab.email }}">{{ tab.email }}</option>
    {% endfor %}
</select>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Usuário</th>
        </tr>
    </thead>
    <tbody>
        {% for tab in table %}
        <tr>
            <td> {{ tab.id }} </td>
            <td> {{ tab.email }} </td>
            <td> 
                <button type="button" class="btn btn-primary btn-sm">editar</button> 
                <button type="button" class="btn btn-danger btn-sm">deletar</button> 
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}